### ISSUE TITLE
items stacking

### ISSUE THREAD

**Issue by idrp** [Coffeelot/cw-prints#1]
I am suggesting to make ["unique"] = true` otherwise items WILL STACK and You'll only be able to see only latest, unless there is a way to name the item on creation.

**Comment by Coffeelot** [comment]
We've looked at ways of solving this. Setting Unique to true will mean that if you split the stack of cards you can't put them together again, which can be kinda silly if you need a stack of like 200 business cards.

Moneybags is an example where they do it like that. The bags can stack when you get them but if you take the stacks apart then you can't stack again. 

Meg, in the discord channel, suggested this: "I think what the person can do is make a stack if business cards (the same) then put them in a stash, then go & make more and have separate stacks of them. That’s the only thing i can come up with"

But, someone might prefer the non restack-able stacks, and in that case all they gotta do is change the unique to true. I can add that in the readme.

**Comment by idrp** [comment]
Yes I am researching how be able to name the item on creation if I find anything will let you know.  Thanks for the reply.  From: CoffeeSent: Monday, 1 August 2022 1:24 AMTo: Coffeelot/cw-printsCc: idRP; AuthorSubject: Re: [Coffeelot/cw-prints] items stacking (Issue #1) We've looked at ways of solving this. Setting Unique to true will mean that if you split the stack of cards you can't put them together again, which can be kinda silly if you need a stack of like 200 business cards.Moneybags is an example where they do it like that. The bags can stack when you get them but if you take the stacks apart then you can't stack again.Meg, in the discord channel, suggested this: "I think what the person can do is make a stack if business cards (the same) then put them in a stash, then go & make more and have separate stacks of them. That’s the only thing i can come up with"But, someone might prefer the non restack-able stacks, and in that case all they gotta do is change the unique to true. I can add that in the readme.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by Coffeelot** [comment]
It would require modifying QBcore stuff, but we think we found a way:
Use something like "stackableUnique" as the ["unique"] value and in QB-inventory, if it has that instead of true/false then compare them on the metadata rather than anything else. 

Just a theory tho, we haven't had time to try it out yet.

**Comment by idrp** [comment]
I just thought of something, not able to test though if you give it to someone and they already have one will it not stack on the one you already have?   From: CoffeeSent: Monday, 1 August 2022 5:50 PMTo: Coffeelot/cw-printsCc: idRP; AuthorSubject: Re: [Coffeelot/cw-prints] items stacking (Issue #1) It would require modifying QBcore stuff, but we think we found a way:Use something like "stackableUnique" as the ["unique"] value and in QB-inventory, if it has that instead of true/false then compare them on the metadata rather than anything else.Just a theory tho, we haven't had time to try it out yet.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by Coffeelot** [comment]
Oh. THAT might be an issue yes. Need to check.

**Comment by idrp** [comment]
Ok so did this: Added this to inventory app.js         } else if (           //idrp addition            itemData.name == "menu" ||            itemData.name == "flyer" ||            itemData.name == "business_card" ||            itemData.name == "coupon"            ) {            $(".item-info-title").html("<p>" + itemData.label + "</p>");            $(".item-info-description").html(                "</span></p><p><strong>Business Name: </strong><span>" +                itemData.info.business +                "</span></p><p><strong>Description: </strong><span>" +                itemData.info.description +                "</span></p><p style=\"font-size:11px\"><b>Weight: </b>" + itemData.weight + " | <b>Amount: </b> " + itemData.amount + " | <b>Quality: </b> " + "<a style=\"font-size:11px;color:green\">" + Math.floor(itemData.info.quality) + "</a>"            );  Added data for description to server.lua local function createBusinessCard(source, data)    local Player = QBCore.Functions.GetPlayer(source)    local item = data[4]    local info = {}    info.business = data[1]    info.url = data[2]    info.description = data[5]    Player.Functions.RemoveMoney("cash", data[3]*Config.Cost)    Player.Functions.AddItem(item, data[3], nil, info)    TriggerClientEvent('inventory:client:ItemBox', source, QBCore.Shared.Items[item], "add")end Added to client.lua            {                text = "Description", -- text you want to be displayed as a place holder                name = "description", -- short description for inventory item                type = "text", -- type of the input                isRequired = true, -- Optional [accepted values: true | false] but will submit the form if no value is inputted            },   Still testing but and need to rework wording.  But could be a work around.  When you print them they stack you can remove one at a time; as unique is set to true you can not restack though.What are your thoughts?    From: CoffeeSent: Monday, 1 August 2022 7:00 PMTo: Coffeelot/cw-printsCc: idRP; AuthorSubject: Re: [Coffeelot/cw-prints] items stacking (Issue #1) Oh. THAT might be an issue yes. Need to check.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by Coffeelot** [comment]
Could you rewrite that on github, or hop in the discord? I think your email or something is completely wrecking your messages haha

**Comment by idrp** [comment]
Ahh ok    From: CoffeeSent: Monday, 1 August 2022 11:52 PMTo: Coffeelot/cw-printsCc: idRP; AuthorSubject: Re: [Coffeelot/cw-prints] items stacking (Issue #1) Could you rewrite that on github, or hop in the discord? I think your email or something is completely wrecking your messages haha—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
