### ISSUE TITLE
NUI Doesnt Close w/ Newspapers / Books

### ISSUE THREAD

**Issue by ohkirby** [Coffeelot/cw-prints#5]
Repro: Make book or newspaper, then open said item, then try to close. Cursor sticks on screen and NUI doesn't close. Restarting script fixes.

**Comment by Coffeelot** [comment]
Do you have any other script using the newspaper item? Issues have been reported before with people using the same item for multiple script, specifically with newspaper.

**Comment by ohkirby** [comment]
> Do you have any other script using the newspaper item? Issues have been reported before with people using the same item for multiple script, specifically with newspaper.

No, unfortunately the newspaper is only used by this script and the issue is persistent. Anything you'd like for me to do to debug?
